"""init

Revision ID: 3872f4772f85
Revises: 
Create Date: 2022-06-19 17:07:03.336155

"""
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3872f4772f85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
